MobileNet - emre570
sezan92/computer-vision-course pull request #11
Opened 2023-12-13 10:16 UTC by emre570

2023-12-13 10:18 UTC, sezan92 requested changes
remove tensorflow version. it is agreed in the main channel to use only pytorch code. moreover there are many overlapping details in the description of the same files

2023-12-13 10:19 UTC, emre570 commented
They gave me how to seperate codes with toggle buttons, but can do it too

2023-12-21 13:39 UTC, sezan92 approved these changes
Looks good

2023-12-22 16:13 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +### Pointwise Seperable Convolutions
```suggestion
### Pointwise Convolutions
```
Pointwise are not separable.

2023-12-22 16:18 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +By replacing regular convolutional layers with these depthwise separable convolutions and pointwise convolutions, MobileNet achieves high accuracy while minimizing computational overhead, making it w
It is either only "depthwise separable convolutions" or "depthwise convolutions and pointwise convolutions".

2023-12-22 16:20 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +This type of convolution applies a single filter (usually 1x1) across all channels in both input and output layers. It has fewer parameters than regular convolution and can be seen as an alternative
maybe mention a "regular convolution usually uses a size of 3x3 or 5x5"

2023-12-22 18:07 UTC, themurtazanazir requested changes
Thanks. This was a great read. Have pointed out some issues. Also, I feel like Depthwise Conv has been explained at three different occasions. Seems a bit redundant.

2023-12-22 18:07 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +   separately (like processing each color individually). This is less work because each filter is small and simple.
```suggestion
 - **Step 1 - Depthwise Convolution:** First, it uses a thin filter (like a single layer of a sponge) for each feature map of the image separately (like processing each color individually). This is less work because each filter is small and simple.
```

2023-12-22 18:07 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +   separately (like processing each color individually). This is less work because each filter is small and simple.
"feature map" instead of just "feature"

2023-12-22 18:07 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +1. **Depthwise convolution:** This step performs a convolution separately for each channel (a single color or feature) in the input image using a small filter (usually 3x3). The output of this step i
How are fewer channels produced using depthwise convolution?

2023-12-22 18:07 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +
In the paper https://arxiv.org/pdf/1704.04861.pdf, they have included BN and ReLU layers as well. 
![image](https://github.com/sezan92/computer-vision-course/assets/34167018/3e2c0cc2-37be-41a6-8c5b-14b3a09b5d15)

2023-12-22 18:19 UTC, themurtazanazir commented on chapters/en/Unit 2 - Convolutional Neural Networks/mobilenet.mdx
> +By replacing regular convolutional layers with these depthwise separable convolutions and pointwise convolutions, MobileNet achieves high accuracy while minimizing computational overhead, making it w
It is either only "depthwise separable convolutions" or "depthwise convolutions and pointwise convolutions".

2024-01-06 09:01 UTC, closed without merging