Googlenet
sezan92/computer-vision-course pull request #12
Opened 2023-12-17 08:10 UTC by albertkao227

My first draft.

2023-12-21 13:34 UTC, sezan92 commented on chapters/en/Unit 2 - Convolutional Neural Networks/googlenet.mdx
> +Before Inception, successful network architectures such as AlexNet or VGG have shown the importance of increasing network depth. However, increasing network depth also increases computation steps, an
```suggestion
Before the Inception model, the successful  architectures such as AlexNet or VGG have shown the importance of increasing the network depth. However, increasing the  depth also increases computational complexity, and problems such as overfitting and/or vanishing gradient may occur. The Inception model introduced a method to efficiently train complex CNNs wih less floating parameters.   
```

2023-12-21 13:35 UTC, sezan92 requested changes
Looks good. Except I feel there are some grammatical mistakes. Is it possible to update using Grammarly free version?

2024-01-04 16:16 UTC, albertkao227 commented
Thanks @sezan92 , revised the sections.

2024-01-04 16:16 UTC, albertkao227 commented on chapters/en/Unit 2 - Convolutional Neural Networks/googlenet.mdx
> +Before Inception, successful network architectures such as AlexNet or VGG have shown the importance of increasing network depth. However, increasing network depth also increases computation steps, an
revised this section

2024-01-04 20:17 UTC, sitamgithub-MSIT reviewed
The writing is good overall!

2024-01-04 20:17 UTC, sitamgithub-MSIT commented on chapters/en/Unit 2 - Convolutional Neural Networks/googlenet.mdx
> +Prior to the advent of the Inception architecture, models like AlexNet and VGG demonstrated the benefits of deeper network structures. However, deeper networks typically entail more computational ste
```suggestion
Before the advent of the Inception architecture, models like AlexNet and VGG demonstrated the benefits of deeper network structures. However, deeper networks typically entail more computational steps and can lead to issues such as overfitting and the vanishing gradient problem. The Inception architecture offers a solution, enabling the training of complex CNNs with a reduced count of floating-point parameters.
```

2024-01-08 15:54 UTC, JvThunder approved these changes
Very good and concise summary of the paper. I have a question though, you wrote of using 9 inception layers yet you only put 8 in the code. You might have missed one layer.

2024-01-12 09:35 UTC, sezan92 approved these changes

2024-01-16 16:02 UTC, merged